name: CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    # - name: Xcodebuild Action
    #   uses: sersoft-gmbh/xcodebuild-action@v2.0
    #   with:
    #     target: Catty
    #     project: ./Catty/Catty.xcodeproj
    - name: Build
      env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        xcode-select --print-path
        cd Catty
        xcodebuild -list -project Catty.xcodeproj
        xcodebuild -project Catty.xcodeproj -scheme Catty
    - name: Run tests
      run: swift test -v
