name: CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Current Xcode
      run: xcode-select --print-path
    - name: List Projects
      run: xcodebuild -list -project ./Catty/Catty.xcodeproj
    - name: Build
      run: xcodebuild -scheme Catty build
    - name: Run tests
      run: swift test -v
