name: CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v2.0
      with:
        scheme: build
        project: ./Catty/Catty.xcodeproj
    - name: Build
      run: |
        xcode-select --print-path
        cd Catty
        xcodebuild -list -project Catty.xcodeproj
        xcodebuild -scheme Catty build
    - name: Run tests
      run: swift test -v
